dist: trusty
sudo: required
services:
- docker

env:
  global:
  - CONTAINER_NAME=debian_container
  - CONTAINER_EXEC="docker exec -t debian_container"
  - DOCKER_REPO=qemu-user-static
  - secure: "VE1n5hqcxJb2uu+HS2gnj1oHRv3J0Ut8Cs91l0WQXDxXbHJrVpeJ9OV81R3nS25BCgbfy6MJoTO6Fy5nI/tPG6xKikPgVEYsY0N3DuJQ9dAVOUMsJ99GClQ8kS5wAwDZ0YKE0ZKi0b/5DFkSxt899TgM5liv1ExpEpYlTnBQfhUvCiw5tuK8EGs8Yw1v6GdhA7HmhnQWgnFeTJ7WF63f7xVTsNnQEe2N/I1WCpkaMV3QXx1Z1/YMQT+1bRxHUhtvyjDLGasMUBmqHFRn/AvgBxk+iiJogMQDE60DG8AEm9idpdkYVJ/oAj59MznHtzN3Xs01A9SzKAtjNc2aO4la946KjSuWJO1W6kmQSQqvLpCrwNO+Fx6shbOa9otWppjNlbWiOBsChN1lgrlTMsvrdMFdVft/L+P8L+NO5Jjtkhy4VyysENR04s566TcDRoEjg5T2uKRnEc5ARJa4cJ9H5eTEnL2S84GGteAPbKcpg7JbbXtd7I7OAdKui8tVwZ2L1LhP1k1qFhoVH6dZp2Z/kcZ2aCZUyIcR6Uz4xaTTeJp+ijywGIxL6KLSiOVVyl46w+SLa5kjRAPiENcaY5iqa+SjK1dxrGL3H7DMPLoEI/eyn6HL0/yjnoMLLHsGlDDXBoxNJc0RjX1fWtrm4xGO9BWdwhHWPOnIu+dIkLcKCnE="

branches:
  only:
  - master

before_install:
- |
  sudo docker run --detach --interactive --tty --privileged \
    --name ${CONTAINER_NAME} \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}" \
    --workdir "${TRAVIS_BUILD_DIR}" \
    debian:sid /bin/bash
- ${CONTAINER_EXEC} apt update -qq
- ${CONTAINER_EXEC} apt install --no-install-recommends -y docker.io qemu-user-static

script:
- ${CONTAINER_EXEC} env DOCKER_USER=${DOCKER_USER} DOCKER_REPO=${DOCKER_REPO} "${TRAVIS_BUILD_DIR}/build.sh"
- docker images | grep ^${DOCKER_USER}/${DOCKER_REPO} | awk '{print $1 ":" $2}'

after_success:
- |
  if [ "${TRAVIS_PULL_REQUEST}" == "false" -a "${TRAVIS_BRANCH}" == "master" ]; then
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
    for image in $(docker images | grep ^${DOCKER_USER}/${DOCKER_REPO} | awk '{print $1 ":" $2}'); do
      docker push $image;
    done
  fi
