dist: trusty
sudo: required
services:
- docker

env:
  global:
  - CONTAINER_NAME=debian_container
  - CONTAINER_EXEC="docker exec -t debian_container"
  - DOCKER_REPO=qemu-user-static
  - secure: "MaxMiayExrgWMcOJYqklAAZIAagAqtk23y8z9x5WUfEqMyS2k/x+zBK1JzmcWXkOnrvbhfNxYttroV/o1y+GwV4wF7Sfxw1Pegt/1PR00BFgEyA8d1/VNkuxv/+w6kE8yyJuGNs/pOVJl7cjBThz4JnMajS8vi4CT8voGWwDNvQ8CnUAWsbOhfcfVJGhWZV8K3JBtJTpHfNhqBjmpxyJP7ohwGtodhnzCLLcO2fvssRtHdB1VBhF8RbROW+/gLB/oavgX5RijMZZ4y2OW4IXG32ku78uGQDinurN3ynSpAHj0FOA4DephjHpA18PhJZTp1VhZDBEMEQvsT3YI8kihasPRpGMtWwdxQbYc1/xN+NOlD6wrUq6iPU8LVHMCqP1sLyxhkRcXF9F2WN2oV7iCKPId5Hus5weKRD5+RotLzDeC0gvljLXBfMicWTDVDppnI4WHYToz4KvxE8hVsqe2p+el4iDvACePT8BksE7g5oeY7nJqMDWKclxMweZZQx4kYUXV/kAIYsUPZ8ft0LfoERiAczC7MNxL3S/bE4wksZDGjPPkqR8yic/H3dI5O7aVcaDNB50cEYYLGShtetUpF/gVCUcT8LsCuc7LNpOEAMMTBhkT5ivE3aXIggi3UyH+EXa6GeGj8SybScZYoA6fyzRL1g/MuJyFI4qQnKD0zs="

branches:
  only:
  - master

before_install:
- |
  sudo docker run --detach --interactive --tty --privileged \
    --name ${CONTAINER_NAME} \
    --volume "${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}" \
    --workdir "${TRAVIS_BUILD_DIR}" \
    debian:sid /bin/bash
- ${CONTAINER_EXEC} apt update -qq
- ${CONTAINER_EXEC} apt install --no-install-recommends -y qemu-user-static

script:
- ${CONTAINER_EXEC} /bin/sh -c 'cp /usr/bin/qemu-*-static .'
- ./build.sh $(${CONTAINER_EXEC} dpkg-query -W -f '\${Version}' qemu-user-static)
- docker images | grep ^${DOCKER_USER}/${DOCKER_REPO} | awk '{print $1 ":" $2}'

after_success:
- |
  if [ "${TRAVIS_PULL_REQUEST}" == "false" -a "${TRAVIS_BRANCH}" == "master" ]; then
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
    for image in $(docker images | grep ^${DOCKER_USER}/${DOCKER_REPO} | awk '{print $1 ":" $2}'); do
      docker push $image;
    done
  fi
